### ISSUE TITLE
When will the code be avillable?

### ISSUE THREAD

**Issue by bittteerr** [luannd/MinutiaeNet#1]
I want to evaluate minutiae net on other data sets. When will the code be released publicly?
Thanks.

**Comment by luannd** [comment]
Hi Bitteerr,

I will upload in March! Please stay tuned!

Thanks!

**Comment by prastika** [comment]
It's March and almost finish, sir

**Comment by colincat321** [comment]
Hi, I want to test minutiae net on a contactless fingerprint dataset. Will the code be public soon?

**Comment by luannd** [comment]
Hi all,
I begin uploading code. Let me know if there are any issues!

**Comment by luannd** [comment]
All codes have been uploaded. Hope you find them useful!

**Comment by vijayanand-Git** [comment]
"Pretrain dir = ../Models/CoarseNet.h5
Traceback (most recent call last):
  File "CoarseNet_train.py", line 68, in <module>
    logging=logging)
  File "D:\new_pc_work\MinutiaeNet-master\CoarseNet\CoarseNet_model.py", line 255, in train
    img_name, folder_name, img_size = get_maximum_img_size_and_names(train_set, None, max_size=input_shape)
  File "D:\new_pc_work\MinutiaeNet-master\CoarseNet\CoarseNet_utils.py", line 367, in get_maximum_img_size_and_names
    if isinstance(dataset, basestring):
NameError: name 'basestring' is not defined"

While Running the CoarseNet_train.py, I am getting an error 'basestring' is not defined. A segment of the error is attached above.
