### ISSUE TITLE
A question on construct_dictionary(ori_num = 30):

### ISSUE THREAD

**Issue by wajihullahbaig** [luannd/MinutiaeNet#10]
I have seen this function, seems like you are building orientation dictionary. 
But Where is it called in the code? I dont understand the usage.

Thanks

**Comment by luannd** [comment]
Hi,
That function is not used. I created to verify the orientation and forgot to clean it. You can remove. The Orientation is calculated in `get_maps_STFT` function.

**Comment by wajihullahbaig** [comment]
Thanks for the reply!
