### ISSUE TITLE
network structure is incorrect?

### ISSUE THREAD

**Issue by wendalegood** [luannd/MinutiaeNet#14]
Hi, luannd. I found that the coarsenet structrue may be incorrect. details below:

level_2=conv_bn_prelu(conv_block3, (256,3,3), '4_1', dilation_rate=(1,1))
level_3=conv_bn_prelu(conv_block2, (256,3,3), '4_2', dilation_rate=(4,4))
level_4=conv_bn_prelu(conv_block2, (256,3,3), '4_3', dilation_rate=(8,8))

you use conv_block2 two times, but according to the paper, you should use conv_block1 for level_4,
and conv_block3 did not do pooling, as we can see, if conv_block2 is 2x than conv_block3, and conv_block1 2x than conv_block2, after "aspp" moudel, they can't be just add directly.

**Comment by luannd** [comment]
The released implementation is the improved version of the paper in which the architecture is slightly different. 
I recommend you our end-to-end system for not only minutiae detection: https://github.com/prip-lab/MSU-LatentAFIS
