### ISSUE TITLE
demo_CoarseNet.ipynb missing 

### ISSUE THREAD

**Issue by wajihullahbaig** [luannd/MinutiaeNet#2]
Thanks for the code, was waiting for this. 
Please note that  the demo folder does not have the demo_CoarseNet.ipynb file

**Comment by wajihullahbaig** [comment]
Any chance you will upload the notebooks??

**Comment by luannd** [comment]
I will notify when it is uploaded.

**Comment by wajihullahbaig** [comment]
Thanks.

**Comment by luannd** [comment]
All codes have been uploaded. Hope you find them useful!
