### ISSUE TITLE
Kernel restarting while testing demo_CoarseNet.ipynb

### ISSUE THREAD

**Issue by wajihullahbaig** [luannd/MinutiaeNet#8]
I was trying to test your code for demoCoarseNet.ipnb, it takes some time for the pre-trained model to load. Once we are at line #82, 
```

        enh_img, enh_img_imag, enhance_img, ori_out_1, ori_out_2, seg_out, mnt_o_out, mnt_w_out, mnt_h_out, mnt_s_out \
            = main_net_model.predict(image)
```

This seems to crash. I suspect out of memory issues on card but I am confident the card does have enough memory. I copied the code to simple text file and ran it in Spyder3, it seems that the above line is causing the kernel to restart in jupyter notebook. Same happens in Spyder3

Spyder 3.2.8
Python 3.6.5
Tensorflow 1.6.0
Keras 2.1.5
Nvidia GTX 960M (4GB )

Did you run into such an issue?

**Comment by luannd** [comment]
It is quite strange. I rechecked but everything is ok. Were you successful running [CoarseNet_run.py](https://github.com/luannd/MinutiaeNet/blob/f6c2c444db1811f5d01bbe00e61790852384bdfa/CoarseNet/CoarseNet_run.py)? If not, the problem might be from your hardware??

**Comment by wajihullahbaig** [comment]
I will try it and let you know. Have not looked into it yet

**Comment by wajihullahbaig** [comment]
OK So  i did some more code conversions for Python3 compatibility. Seems that the problem is persisting even in CoarseNet_run.py. My laptop has 16 GB of memory and code peaks at 14.9 before the kernel restarts. I suspect a problem with Tensorflow?

**Comment by wajihullahbaig** [comment]
Yep - It was a tensorflow issue. I updated tensorflow 1.8.0 and keras to 2.2.0. The error is gone now.

**Comment by luannd** [comment]
Cool. Glad you fixed it!
